/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socks;

import java.io.IOException;
import java.nio.channels.ServerSocketChannel;

public class App {
    public static int DEFAULT_PORT = 1112;

    public static void main(String[] args) throws IOException {
        int port = args.length > 0 ? Integer.parseInt(args[0]) : DEFAULT_PORT;
        final SocksServer socksServer = new SocksServer(port);
        socksServer.serveConnections();
    }
}
