/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socks;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;


class AppTest {
    @Test void clientConnectsToServer() throws IOException {
        Socket socket = new Socket();
        socket.connect(new InetSocketAddress("127.0.0.1", 1112));
        OutputStream out  = socket.getOutputStream();
        out.write(new byte[] {0x05, 0, 0});
        InputStream in = socket.getInputStream();
        byte []buffer = new byte[256];
        int read = in.read(buffer);
        log.debug("Received from server: " + Arrays.toString(Arrays.copyOfRange(buffer, 0, read)));

        out.write(new byte[] {0x05, 0x01, 0x00, 0x03, (byte) ("weather.nsu.ru".getBytes(StandardCharsets.UTF_8).length)});
        out.write("weather.nsu.ru".getBytes(StandardCharsets.UTF_8));
        out.write(new byte[]{0x00, 80});

        out.write(new byte[]{ 66, 66});

        read = in.read(buffer);
        log.debug("Received from server: " + Arrays.toString(Arrays.copyOfRange(buffer, 0, read)));

    }
}
