/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socks;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void clientConnectsToServer() throws IOException {
        Socket socket = new Socket();
        socket.connect(new InetSocketAddress("127.0.0.1", 1112));
        socket.getOutputStream().write("how do you do?".getBytes(StandardCharsets.UTF_8));
    }
}
